//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.20 at 12:03:07 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.adilmx.com/soap")
package com.adilmx.soap;
